{% set version = '1.0-4' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nortest
  version: {{ version|replace("-", "_") }}

source:
  fn: nortest_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/nortest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nortest/nortest_{{ version }}.tar.gz
  sha256: a3850a048181d5d059c1e74903437569873b430c915b709808237d71fee5209f

build:
  noarch: generic
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('nortest')"           # [not win]
    - "\"%R%\" -e \"library('nortest')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nortest
  license: GPL-2.0-or-later
  summary: Five omnibus tests for testing the composite hypothesis of normality.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
